# Generated by Django 4.0.4 on 2022-05-07 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("-created_at",), "verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name": "Order Item", "verbose_name_plural": "Order Items"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("-created_at",), "verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
    ]
